version: "3.3"

services:
  #custom-image
  app-laravel-stock-flow:
    build:
      args:
        user: odenilson
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: odenilson/app-stock-flow
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: always
    networks:
      - net-stock-flow

  #nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8180:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - net-stock-flow

  #db
  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3387:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - net-stock-flow

  #redis
  redis:
    image: redis:latest
    networks:
      - net-stock-flow

networks:
  net-stock-flow:
    driver: bridge
